apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::841002843554:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4BGVCGDKNR9C
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::841002843554:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-24T18:18:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "902"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fec29cdf-a172-4734-aef2-9407130e3e87
